/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan6;

import Tuan6.Employees;
import Tuan6.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.omg.CosNaming.NamingContextExtPackage.StringNameHelper;


public class frmEmployees extends javax.swing.JFrame {
    
    
    private ArrayList<Employees> list ;
    DefaultTableModel model;

    public frmEmployees() {
        initComponents();
        this.setLocationRelativeTo(null);
        //tao ra mot list moi lay gia tri tu ham getAllEmployees ben kia
        list = new DBConnection().getAllEmployees();
        model=(DefaultTableModel)jtbEmployees.getModel();
         model.setColumnIdentifiers(new Object[]{
            "ID", "Name", "Address", "Genner", "knowledge" , "subject"
        });
       showTable();
        System.out.println("");
    }
    
    //ham hien thng tin len table;
    public void showTable(){
        for(Employees listEmployees :list ){
            model.addRow(new Object []{
                listEmployees.getId(),
                listEmployees.getName(),
                listEmployees.getAddress(),
                listEmployees.getGender(),
                listEmployees.getKnowledge(),
                listEmployees.getSubject(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblKnow = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        radiMale = new javax.swing.JRadioButton();
        radiFemale = new javax.swing.JRadioButton();
        chkJava = new javax.swing.JCheckBox();
        chkPython = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbEmployees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cboSub = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name");
        lblName.setName("lblName"); // NOI18N

        lblAdress.setText("Address");
        lblAdress.setName("lblAddress"); // NOI18N

        lblGender.setText("Gender");
        lblGender.setName("lblGender"); // NOI18N

        lblKnow.setText("Knowledge");
        lblKnow.setName("lblKnowledge"); // NOI18N

        lblSub.setText("Subject");
        lblSub.setName("lblSubject"); // NOI18N

        txtName.setName("txtName"); // NOI18N

        txtAddress.setName("txtAddress"); // NOI18N

        buttonGroup1.add(radiMale);
        radiMale.setText("Male");
        radiMale.setName("radiMale"); // NOI18N

        buttonGroup1.add(radiFemale);
        radiFemale.setText("Female");
        radiFemale.setName("radiFemale"); // NOI18N

        buttonGroup2.add(chkJava);
        chkJava.setText("Java");
        chkJava.setName("chkJava"); // NOI18N

        buttonGroup2.add(chkPython);
        chkPython.setText("Python");
        chkPython.setName("chkPython"); // NOI18N

        btnSave.setText("Save");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setName("btnReset"); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jtbEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Gender", "Knowledge", "Subject"
            }
        ));
        jtbEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbEmployeesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbEmployees);

        jLabel1.setText("ID");

        cboSub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mangement", "Bussiness", "Education", "Developer" }));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblAdress)
                            .addComponent(lblGender)
                            .addComponent(lblKnow)
                            .addComponent(lblSub)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiMale)
                                    .addComponent(chkJava))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPython)
                                    .addComponent(radiFemale)))
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtId)
                            .addComponent(cboSub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdress)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(radiMale)
                            .addComponent(radiFemale))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKnow)
                            .addComponent(chkJava)
                            .addComponent(chkPython))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblSub))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnReset)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Employees employees = new Employees();
        employees.setId(Integer.parseInt(txtId.getText()));
        employees.setName(txtName.getText());
        employees.setAddress(txtAddress.getText());

         if (radiMale.isSelected()) {
            employees.setGender("nam");

        } else {
            employees.setGender("nu");
        }
        
          if (chkJava.isSelected() && chkPython.isSelected()) {
            employees.setKnowledge("Java + Python");

        } else if(chkJava.isSelected()){
           employees.setKnowledge("@Java");
        } else if(chkPython.isSelected()){
           employees.setKnowledge("@Python");
        }
          employees.setSubject(cboSub.getSelectedItem().toString());
         
         if( new DBConnection().addEmployees(employees)){
             JOptionPane.showMessageDialog(rootPane, "Luu thanh cong");
             list.add(employees);
             showEmployees();
         } else {
             JOptionPane.showMessageDialog(rootPane, "Faill");
         }   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtbEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbEmployeesMouseClicked
        // TODO add your handling code here:
        //lay index(chi so dong) cua table
        int i = jtbEmployees.getSelectedRow();
        //lay du lieu trong table
        TableModel model = jtbEmployees.getModel();
        txtName.setText(model.getValueAt(i, 1).toString());
        txtAddress.setText(model.getValueAt(i, 2).toString());
        String gender= model.getValueAt(i, 3).toString();
        if(gender.equals("Nam")){
            radiMale.setSelected(true);
        }
        else{
            radiFemale.setSelected(true);
        }
        String knowledge= model.getValueAt(i, 4).toString();
        switch(knowledge){
            case "Java":
                chkJava.setSelected(true);
                chkPython.setSelected(false);
                break;
            case "Python":
                chkJava.setSelected(false);
                chkPython.setSelected(true);
                break; 
            default:
                chkJava.setSelected(true);
                chkPython.setSelected(true);
                break;         
        }
       String subject =model.getValueAt(i, 5).toString().trim();
                switch(subject){
                    case "Mangement":
                        cboSub.setSelectedIndex(0);
                        break;
                    case "Bussiness":
                        cboSub.setSelectedIndex(1);
                        break;
                    case "Education":
                        cboSub.setSelectedIndex(2);
                        break;
                    case "Developer":
                        cboSub.setSelectedIndex(3);
                        break;
    }//GEN-LAST:event_jtbEmployeesMouseClicked
}
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Connection conn = null; //tao doi tuong ket noi moi = gia tri rong
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            try {
                //gan gia tri cho conn 
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433 ; databaseName=DBEMPLOY ; user=sa ; password=hieu123");
                System.out.println("ket noi thanh cong");
            } catch (SQLException ex) {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("khong tim thay database");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println("khong tim thay driver");
        }
        int rowIndex = jtbEmployees.getSelectedRow();
        //ID cua3 nhan6 vien6 ta click vao2 table
        String id = jtbEmployees.getModel().getValueAt(rowIndex, 0).toString();
        //Cau6 queery dung2 cho update
         ArrayList<Employees> listEmployees  = new ArrayList<>();
        //Connection conn = DBConnection.getConnection();
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from emloyee");
            while(rs.next()){
                //int id= rs.getInt("id");
                String name= rs.getString("name");
                String address= rs.getString("address");
                String gender= rs.getString("gender");
                String knowledge= rs.getString("knowledge");
                String subject= rs.getString("subject");
                
                Employees employee = new Employees(id, name, address, gender, knowledge, subject);
                listEmployees.add(employee);
            }
        } catch (Exception e) {
        }
        Employees employee = new Employees();
        employee.setId(Integer.parseInt(txtId.getText()));
        employee.setName(txtName.getText());
        employee.setAddress(txtAddress.getText());

         if (radiMale.isSelected()) {
            employee.setGender("Nam");

        } else {
            employee.setGender("Nu");
        }
        
          if (chkJava.isSelected() && chkPython.isSelected()) {
            employee.setKnowledge("Java + Python");

        } else if(chkJava.isSelected()){
           employee.setKnowledge("@Java");
        } else if(chkPython.isSelected()){
           employee.setKnowledge("@Python");
        }
          employee.setSubject(cboSub.getSelectedItem().toString());
         new DBConnection().addEmployees(employee);
         list = new DBConnection().getAllEmployees();
        model=(DefaultTableModel)jtbEmployees.getModel();
         model.setColumnIdentifiers(new Object[]{
            "ID", "Name", "Address", "Genner", "knowledge" , "subject"
        });
             list.add(employee);
             JOptionPane.showMessageDialog(rootPane, "Update thanh cong");
             
             
         /*if( new DBConnection().addEmployees(employee)){
             JOptionPane.showMessageDialog(rootPane, "Update thanh cong");
             list.add(employee);
             showEmployees();
         } else {
             JOptionPane.showMessageDialog(rootPane, "Faill");
         }*/
         
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       /* int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete", JOptionPane.YES_NO_OPTION);
        
        Connection conn = null; //tao doi tuong ket noi moi = gia tri rong
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            try {
                //gan gia tri cho conn 
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433 ; databaseName=DBEMPLOY ; user=sa ; password=hieu123");
                System.out.println("ket noi thanh cong");
            } catch (SQLException ex) {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("khong tim thay database");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println("khong tim thay driver");
        }
        int rowIndex = jtbEmployees.getSelectedRow();
        //ID cua nhan vien6 ma2 ta click
        String ID= jtbEmployees.getModel().getValueAt(rowIndex, 0).toString();
        //câu queery dùng cho update
        String sql= "delete from employee where id="+ID;
        PreparedStatement preStmt= null;
        int rowDelete = 0;
        try {
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433 ; databaseName=DBEMPLOY ; user=sa ; password=hieu123");
            preStmt= conn.prepareStatement(sql);
            rowDelete = preStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            conn.close();
            preStmt.close();
            //làm rỗng table
            DefaultTableModel model= (DefaultTableModel)jtbEmployees.getModel();
            model.setRowCount(0);
            //làm mói dữ table
            showEmployees();
            System.out.println("Row inserted"+rowDelete);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtAddress.setText("");
        radiMale.setSelected(true);
        chkJava.setSelected(false);
        chkPython.setSelected(false);
        cboSub.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    public static Connection getConnection(){
        Connection conn = null; //tao doi tuong ket noi moi = gia tri rong
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            try {
                //gan gia tri cho conn 
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433 ; databaseName=DBEMPLOY ; user=sa ; password=hieu123");
                System.out.println("ket noi thanh cong");
            } catch (SQLException ex) {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("khong tim thay database");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println("khong tim thay driver");
        }
        return conn; //tra ve gia tri la conn
    }
    //ham update sau khi them du lieu vao
    public void showEmployees(){
        Employees employees = list.get(list.size()-1);
        model.addRow(new Object[]{
            employees.getId() , 
            employees.getName(),
            employees.getAddress(),
            employees.getGender(),
            employees.getKnowledge(),
            employees.getSubject(),
        });
    }
       

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboSub;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkPython;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbEmployees;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblKnow;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSub;
    private javax.swing.JRadioButton radiFemale;
    private javax.swing.JRadioButton radiMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
