/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan3;

/**
 *
 * @author Hieu
 */
public class LAB2_CALCURLATOR extends javax.swing.JFrame {

    /**
     * Creates new form test3
     */
    public LAB2_CALCURLATOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hienThi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        So1 = new javax.swing.JButton();
        So2 = new javax.swing.JButton();
        So3 = new javax.swing.JButton();
        Chiahet = new javax.swing.JButton();
        can = new javax.swing.JButton();
        So4 = new javax.swing.JButton();
        So5 = new javax.swing.JButton();
        So6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        chiadu = new javax.swing.JButton();
        So7 = new javax.swing.JButton();
        So8 = new javax.swing.JButton();
        So9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        phanso = new javax.swing.JButton();
        So0 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Cong = new javax.swing.JButton();
        Bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo");

        jPanel1.setLayout(new java.awt.BorderLayout());

        hienThi.setText("0");
        hienThi.setName("lblhienThi"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(4, 5));

        So1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So1.setText("1");
        So1.setName("btn1"); // NOI18N
        So1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So1ActionPerformed(evt);
            }
        });
        jPanel3.add(So1);

        So2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So2.setText("2");
        So2.setName("btn2"); // NOI18N
        So2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So2ActionPerformed(evt);
            }
        });
        jPanel3.add(So2);

        So3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So3.setText("3");
        So3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So3ActionPerformed(evt);
            }
        });
        jPanel3.add(So3);
        So3.getAccessibleContext().setAccessibleName("btn3");

        Chiahet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Chiahet.setText("/");
        Chiahet.setName("btnchiahet"); // NOI18N
        Chiahet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiahetActionPerformed(evt);
            }
        });
        jPanel3.add(Chiahet);

        can.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        can.setText("sqrt");
        can.setName("btnsprt"); // NOI18N
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        jPanel3.add(can);

        So4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So4.setText("4");
        So4.setName("btn4"); // NOI18N
        So4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So4ActionPerformed(evt);
            }
        });
        jPanel3.add(So4);

        So5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So5.setText("5");
        So5.setName("btn5"); // NOI18N
        So5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So5ActionPerformed(evt);
            }
        });
        jPanel3.add(So5);

        So6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So6.setText("6");
        So6.setName("btn6"); // NOI18N
        So6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So6ActionPerformed(evt);
            }
        });
        jPanel3.add(So6);

        nhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nhan.setText("*");
        nhan.setName("btnnhan"); // NOI18N
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPanel3.add(nhan);

        chiadu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chiadu.setText("%");
        chiadu.setName("btnchiadu"); // NOI18N
        chiadu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaduActionPerformed(evt);
            }
        });
        jPanel3.add(chiadu);

        So7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So7.setText("7");
        So7.setName("btn7"); // NOI18N
        So7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So7ActionPerformed(evt);
            }
        });
        jPanel3.add(So7);

        So8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So8.setText("8");
        So8.setName("btn8"); // NOI18N
        So8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So8ActionPerformed(evt);
            }
        });
        jPanel3.add(So8);

        So9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So9.setText("9");
        So9.setName("btn9"); // NOI18N
        So9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So9ActionPerformed(evt);
            }
        });
        jPanel3.add(So9);

        tru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tru.setText("-");
        tru.setName("btntru"); // NOI18N
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPanel3.add(tru);

        phanso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phanso.setText("1/x");
        phanso.setName("btnPhanSo"); // NOI18N
        phanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phansoActionPerformed(evt);
            }
        });
        jPanel3.add(phanso);

        So0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        So0.setText("0");
        So0.setName("btn0"); // NOI18N
        So0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So0ActionPerformed(evt);
            }
        });
        jPanel3.add(So0);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setText("+/-");
        jButton16.setName("btnAm"); // NOI18N
        jPanel3.add(jButton16);

        Xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Xoa.setText("C");
        Xoa.setName("btnXoa"); // NOI18N
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });
        jPanel3.add(Xoa);

        Cong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cong.setText("+");
        Cong.setName("btnCong"); // NOI18N
        Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CongActionPerformed(evt);
            }
        });
        jPanel3.add(Cong);

        Bang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bang.setText("=");
        Bang.setName("btnBang"); // NOI18N
        Bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BangActionPerformed(evt);
            }
        });
        jPanel3.add(Bang);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void So1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So1ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So1.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So1ActionPerformed

    private void So2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So2ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So2.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So2ActionPerformed

    private void So3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So3ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So3.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So3ActionPerformed

    private void So4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So4ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So4.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So4ActionPerformed

    private void So5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So5ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So5.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So5ActionPerformed

    private void So6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So6ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So6.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So6ActionPerformed

    private void So7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So7ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So7.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So7ActionPerformed

    private void So8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So8ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So8.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So8ActionPerformed

    private void So9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So9ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So9.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So9ActionPerformed

    private void So0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So0ActionPerformed
        // TODO add your handling code here:
        String gt=this.hienThi.getText();
        if(gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt + So0.getText());
            this.hienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_So0ActionPerformed
    private long a =0;
    private String phepToan="";
    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "sqrt";
        this.hienThi.setText("0");
    }//GEN-LAST:event_canActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "*";
        this.hienThi.setText("0");
    }//GEN-LAST:event_nhanActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "-";
        this.hienThi.setText("0");
    }//GEN-LAST:event_truActionPerformed

    private void CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CongActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "+";
        this.hienThi.setText("0");
    }//GEN-LAST:event_CongActionPerformed

    private void ChiahetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiahetActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "/";
        this.hienThi.setText("0");
    }//GEN-LAST:event_ChiahetActionPerformed

    private void chiaduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaduActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "%";
        this.hienThi.setText("0");
    }//GEN-LAST:event_chiaduActionPerformed

    private void phansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phansoActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.hienThi.getText());
        this.phepToan = "*";
        this.hienThi.setText("0");
    }//GEN-LAST:event_phansoActionPerformed

    private void BangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BangActionPerformed
        // TODO add your handling code here:
        if(this.phepToan.length()>0){
            long b=Long.parseLong(this.hienThi.getText());
            if(this.phepToan.equals("+")){
                long kq=this.a+b;
                this.hienThi.setText(String.valueOf(kq));
            }
            else if(this.phepToan.equals("-")){
            long kq=this.a-b;
            this.hienThi.setText(String.valueOf(kq));
        }
            else if(this.phepToan.equals("/")){
            float kq=(float)this.a/b;
            this.hienThi.setText(String.valueOf(kq));
        }
            else if(this.phepToan.equals("*")){
            long kq=this.a*b;
            this.hienThi.setText(String.valueOf(kq));
            }
            this.phepToan ="";
            this.a=0;
            }
    }//GEN-LAST:event_BangActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_XoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB2_CALCURLATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB2_CALCURLATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB2_CALCURLATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB2_CALCURLATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB2_CALCURLATOR().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bang;
    private javax.swing.JButton Chiahet;
    private javax.swing.JButton Cong;
    private javax.swing.JButton So0;
    private javax.swing.JButton So1;
    private javax.swing.JButton So2;
    private javax.swing.JButton So3;
    private javax.swing.JButton So4;
    private javax.swing.JButton So5;
    private javax.swing.JButton So6;
    private javax.swing.JButton So7;
    private javax.swing.JButton So8;
    private javax.swing.JButton So9;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton can;
    private javax.swing.JButton chiadu;
    private javax.swing.JLabel hienThi;
    private javax.swing.JButton jButton16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phanso;
    private javax.swing.JButton tru;
    // End of variables declaration//GEN-END:variables
}
